### ISSUE TITLE
can't get the sveltekit update to work with this one

### ISSUE THREAD

**Issue by j2l** [timsonner/SvelteKitSystemCall#8]
Hello,
The project needs an update. I tried to find how to do it to PR but I didn't succeed since https://github.com/sveltejs/kit/pull/3384#issuecomment-1077640455
Any idea?

**Comment by timsonner** [comment]
I'm going to look into this, I haven't done much with Svelte lately, so I need to dust off the cobwebs. Have you tried the Svelte discord channels? Someone there can probably assist more quickly than I, but I will see about getting this up and running, see what I find.

**Comment by j2l** [comment]
I didn't try discord. 
I'm usually frustrated with it and StackOverflow :smile:

**Comment by timsonner** [comment]
Latest and greatest. I have no idea what errors you encountered, but there have been breaking changes for sure. The primary change concerning this project is the RequestHandler. There is also the issue of having to remove the line "target" from svelte.config.js. I also ran 'npm upgrade' before doing anything. New import statement style as well. Got this running by hacking at my /src/routes/api/index.json.ts file, it looks like:

import { spawn } from "child_process"
/** @type {import('@sveltejs/kit').RequestHandler} */

let output: string = ``

function makeSystemCall(): void {
    const systemCall = spawn(`ls`, [`-al`])

    systemCall.stdout.on(`data`, (data) => {
        output += data
        console.log(`stdout: ${data}`)
    })

    systemCall.stderr.on(`data`, (data) => {
        console.error(`stderr: ${data}`)
    })

    systemCall.on(`close`, (code) => {
        console.log(`child process exited with code ${code}`)
    })
}

// 04/06/2022 @ 2:30AM This looks to be the new way to make a request

export async function get() {
    
        makeSystemCall()
        return {
            body: output
        
    }
}

**Comment by j2l** [comment]
I'll try ASAP!

**Comment by j2l** [comment]
Working, thank you @timsonner !
I only changed to `body: { output }` to get a valid object.
Fixed!
